### ISSUE TITLE
Consider publishing to open-vsx

### ISSUE THREAD

**Issue by t-gebauer** [nix-community/vscode-nix-ide#17]
The libre distribution of VS Code (VS Codium) is now by default configured to use https://open-vsx.org/ instead of the Microsoft Marketplace for licensing reasons.

https://github.com/VSCodium/vscodium/blob/master/DOCS.md#extensions-marketplace

Please consider publishing the extension there.
Wiki Guide https://github.com/eclipse/openvsx/wiki/Publishing-Extensions

Alternatively one can request their CI to [publish the extension for you](https://github.com/eclipse/openvsx/wiki/Namespace-Access#the-open-vsx-account) by adding it to the list in https://github.com/open-vsx/publish-extensions

**Comment by 1000101** [comment]
Oh my, I was completely oblivious to this repo so I've created PR for the old plugin here: https://github.com/open-vsx/publish-extensions/pull/189 ...please, be so kind and publish this extensions and I'll remove the support for the old one.

**Comment by jnoortheen** [comment]
Sure I will setup an action to publish to both registries in one or two days.

**Comment by jnoortheen** [comment]
published [here](https://open-vsx.org/extension/jnoortheen/nix-ide)

**Comment by JamieMagee** [comment]
@jnoortheen You might want to [claim the namespace](https://github.com/eclipse/openvsx/wiki/Namespace-Access)

> The namespace jnoortheen is public, which means that everyone can publish new versions of the “Nix IDE” extension. If you would like to become the owner of jnoortheen, please read this guide.

**Comment by jnoortheen** [comment]
> @jnoortheen You might want to [claim the namespace](https://github.com/eclipse/openvsx/wiki/Namespace-Access)
> 
> > The namespace jnoortheen is public, which means that everyone can publish new versions of the “Nix IDE” extension. If you would like to become the owner of jnoortheen, please read this guide.

Yes have already opened a PR.
