### ISSUE TITLE
Get `Failed to run nixpkgs-fmt: spawn nixpkgs-fmt ENOENT` error

### ISSUE THREAD

**Issue by nikitavoloboev** [nix-community/vscode-nix-ide#174]
Every time I save a file ([default.nix](https://code.tvl.fyi/tree/default.nix)) in my case, I get above error. I have Nix installed on macOS. This nix code from the file formats perfectly well with https://nix-community.github.io/nixpkgs-fmt/ so it's something with extension not working. 

I actually tested it myself on my macOS terminal and got:

```
❯ nixpkgs-fmt default.nix
default.nix
1 / 1 have been reformatted
```

So something is going wrong in VSCode, can I see the logs somewhere?

**Comment by jnoortheen** [comment]
I think, the VSCode is not able to find nixpkgs-fmt in the PATH. You can put the full path to the executable in the configuration page.

**Comment by nikitavoloboev** [comment]
That worked, thanks.
