### ISSUE TITLE
`punctuation.definition.attrset-or-function.nix` doesn't allow antiquotation as first key

### ISSUE THREAD

**Issue by lilyball** [nix-community/vscode-nix-ide#189]
If I have an attrset with a newline after the `{` in a position that admits functions, this is scoped as `punctuation.definition.attrset-or-function.nix`. In this context, if the first key is an antiquotation, it flags this as a syntax error. Besides being an incorrect error, this can cause the rest of the file to tokenize incorrectly as well.

As an example, see [`lib/generators.nix` in nixpkgs](https://github.com/NixOS/nixpkgs/blob/c32c39d6f3b1fe6514598fa40ad2cf9ce22c3fb7/lib/generators.nix#L177). This also highlights incorrectly in GitHub of course. Sample extract:

```nix
{
  # …
  recurse = path: value:
    # …
    if length path > 1 then {
      ${concatStringsSep "." (lib.reverseList (tail path))}.${head path} = value;
    } else {
      ${head path} = value;
    };
}
```

In this example, the rest of the line ends up being treated as inside a double-quoted string, and so the rest of the file is highlighted incorrectly.

This particular issue is actually something I fixed in my `vscode-nix` fork a year ago, see https://github.com/lilyball/vscode-nix/commit/2a7db0fe19db97fd67bbd6d64a6330d66d9e8c3c, but I'm not in a position to port this to `vscode-nix-ide` or open any PRs at the moment.

**Comment by jnoortheen** [comment]
Thanks for the input @lilyball
