### ISSUE TITLE
Contribute to nix-community?

### ISSUE THREAD

**Issue by JamieMagee** [nix-community/vscode-nix-ide#2]
I started working on a similar project over the weekend ([JamieMagee/vscode-nix](https://github.com/JamieMagee/vscode-nix)), and I just discovered your project as well! I don't really want to duplicate any effort, so I think I should contribute to your extension instead.

I was wondering if you would consider re-homing your extension to [nix-community](https://github.com/nix-community) and maintaining it there? There was an ask to do this on the existing extension (bbenoist/vscode-nix#6), but the maintainer there appears to be missing. I think that with your extension, the community could more easily contribute (I know I would) and it would be more discoverable for Nix users.

What do you think?

**Comment by JamieMagee** [comment]
cc: @grahamc as you initially suggested the idea on the other extension

**Comment by jnoortheen** [comment]
Sure. How should I start it?

**Comment by JamieMagee** [comment]
Let's wait and see what Graham's response is.

**Comment by JamieMagee** [comment]
@jnoortheen I asked in the nix forum https://discourse.nixos.org/t/nix-vscode-extension/9117

**Comment by jnoortheen** [comment]
I think the core developers mainly use emacs and not concentrating much on other editors. the language server looks great though.

**Comment by JamieMagee** [comment]
True, but I think there are clearly people who would be interested in this and we should be meeting users where they are, with their own tools, instead of forcing other tools onto them.

**Comment by grahamc** [comment]
Sounds like a good idea :) I'll cc nix-community

**Comment by Mic92** [comment]
@JamieMagee @jnoortheen I sent you both an invite.

**Comment by JamieMagee** [comment]
@Mic92 Thanks! I've accepted the invite. I would recommend migrating @jnoortheen's repo, as it's further along in development than the one I created.

**Comment by jnoortheen** [comment]
I am transfering the repo.

**Comment by jnoortheen** [comment]
moved the repo. 

Thanks @JamieMagee  @Mic92 

PR welcome for Language Server feature.

**Comment by Mic92** [comment]
I moved you both in a team where you can do maintain the repo.

**Comment by jnoortheen** [comment]
@Mic92 I need to set some secrets, to publish using GitHub actions. Could you enable access for it?

**Comment by jnoortheen** [comment]
https://open-vsx.org/extension/jnoortheen/nix-ide

**Comment by jnoortheen** [comment]
Any updates? @Mic92 I am not sure whom I could ping for this.

**Comment by Mic92** [comment]
@jnoortheen I increased the privileges to include `admin` rights. You should be now able to add secrets. Otherwise ping @Mic92 on IRC in #nix-community

**Comment by Mic92** [comment]
I changed the default branch from master to main.

**Comment by jnoortheen** [comment]
> I changed the default branch from master to main.

Thanks. I will check it this weekend.
