### ISSUE TITLE
Antiquotation inside paths is broken

### ISSUE THREAD

**Issue by lilyball** [nix-community/vscode-nix-ide#236]
As of Nix 2.4, antiquotations are allowed in paths. The only restriction is the path must contain a slash prior to any antiquotations. This means that `./${foo}-${bar}.nix` is a valid path, whereas `a.${foo}/b.${bar}` is a division operation.

The syntax currently does not know about this. It accepts antiquotations in paths under some conditions by parsing it as a different sequence of tokens, e.g. it will accept `import /${x}/bar`, which it appears to be doing by parsing the `/` as a division operator and then accepting `${x}/bar` as an argument for no good reason. It also takes `import ./${x}/bar`, although in this case adding the space like `import ./ ${x}/bar` produces an error and I'm not quite sure what's going on with this parse. When used as the RHS of a let-binding it will highlight the leading `/` or `./` as invalid (but will not mark this as an error).

However, what is a hard error is stuff like `/${x}.nix`. This construct doesn't just highlight the `.nix` as wrong, it highlights the entire rest of the file too. This is really frustrating as antiquotations in paths is far more convenient than concatenating with `+`. It's also annoying to have things like `./${x}/bar` have their prefix highlighted as invalid, but that's at least tolerable as there's no error placed there. The error I get with `/${x}.nix` is bad enough that it makes this whole syntax feature unusable.

**Comment by uncenter** [comment]
Isn't this a duplicate of your other issue, #196?

**Comment by lilyball** [comment]
Looks like yes, I must have forgotten in the intervening 5 months.
