### ISSUE TITLE
Mark unused attributes?

### ISSUE THREAD

**Issue by wmertens** [nix-community/vscode-nix-ide#273]
I'm wondering if this extension can somehow leverage rnix-lsp to find out which attributes are unused in an expression.

Example:
```nix
let a=5; b=true; in b
```

would mark `a` as unused.

**Comment by hall** [comment]
I've not terribly familiar with language servers but just wanted to add that using [nil](https://github.com/oxalica/nil), as mentioned in #274, marks attributes as unused (see `inputs` and `pkgs` in the screenshot below). So my guess is that whatever change needs to happen, should happen in [rnix-lsp](https://github.com/nix-community/rnix-lsp) (though I could be wrong).

![image](https://user-images.githubusercontent.com/32495955/189428535-77727067-0c78-478c-9a14-0eaacfc3ad47.png)

**Comment by jnoortheen** [comment]
As @hall has mentioned, the info would come from LSP servers.
