### ISSUE TITLE
`nil` lsp support

### ISSUE THREAD

**Issue by viperML** [nix-community/vscode-nix-ide#274]
Hello 👋 

[nil](https://github.com/oxalica/nil) is a new nix LSP. By changing this setting to use it instead of `rnix-lsp` seems to work fine:

```jsonc
{
  // ...
  "nix.serverPath": "nil"
}
```

But I wonder if anything else would be necessary from this extension to improve the integration.

Related: https://github.com/oxalica/nil/pull/6

**Comment by hall** [comment]
Not the maintainer but my understanding of the language server protocol is that half the point is it's implementation agnostic so swapping `rnix-lsp` of `nil` should be fairly transparent. I did the same brief test you did and got the same result which is encouraging :slightly_smiling_face: I even noticed _extra_ functionality out of the box with `nil` (see https://github.com/nix-community/vscode-nix-ide/issues/273#issuecomment-1242382829) so I don't think this extension is overly tied to `rnix-lsp`.

My suggestion is that we can "declare" support for `nil` (e.g., as done in #276) and then address individual issues separately as they come up. But that's not my call to make.

**Comment by wmertens** [comment]
Indeed, nil seems to work great!

**Comment by jnoortheen** [comment]
> My suggestion is that we can "declare" support for nil (e.g., as done in https://github.com/nix-community/vscode-nix-ide/pull/276) and then address individual issues separately as they come up

I completely agree. Any LSP servers would be compatible. It is a community project and any effort to make it more usable without affecting existing users are welcome.
