### ISSUE TITLE
Nix IDE does not respect formatter path

### ISSUE THREAD

**Issue by schuelermine** [nix-community/vscode-nix-ide#287]
I’ve set `nix.formatterPath` to `nixfmt` and a store path for `nixfmt`, but it still uses `nixpkgs-fmt`.

**Comment by hall** [comment]
Do you have `nix.enableLanguageServer` set to `true`? If so, the extension doesn't [register a document formatter](https://github.com/nix-community/vscode-nix-ide/blob/a96c25fe9f729007d57e945d060f327c19ef7341/src/extension.ts#L21-L30), effectively ignoring `nix.formatterPath`, and instead relies on the language server to provide formatting (which, in the case of `rnix-lsp`, is provided by `nixpkgs-fmt`).

**Comment by schuelermine** [comment]
Yes, I do have that on. Thanks for the information.
