### ISSUE TITLE
create github actions

### ISSUE THREAD

**Issue by jnoortheen** [nix-community/vscode-nix-ide#3]
- [x] 1. to check the commit message format is in `conventional commit style`

- [x] 2. uploads to vscode extensions page upon pushing tags

**Comment by JamieMagee** [comment]
I've had good success with zeke/semantic-pull-requests for enforcing conventional commit messages

**Comment by jnoortheen** [comment]
Thanks @JamieMagee . I have requested its integrations.

**Comment by JamieMagee** [comment]
Is it also possible to request [Renovate](https://github.com/marketplace/renovate)? I'd like to use it to manage dependency updates.

**Comment by SuperSandro2000** [comment]
> I've had good success with [zeke/semantic-pull-requests](https://github.com/zeke/semantic-pull-requests) for enforcing conventional commit messages

and everything I got to listen about such bots is negative, rage and not contributing because the bot is annoying.

**Comment by jnoortheen** [comment]
upon merging one can easily squash/rebase and put a new commit message. It doesn't entirely fall on the contributors shoulders.

**Comment by jnoortheen** [comment]
> Is it also possible to request [Renovate](https://github.com/marketplace/renovate)? I'd like to use it to manage dependency updates.

I am not able to add it for this repo. I think the default dependabot is sufficient.

**Comment by jnoortheen** [comment]
added GitHub action to publish. Though it will fail until the secrets are set which needs to be set once the permission is granted.

**Comment by zowoq** [comment]
> I have requested its integrations.

I just noticed this was pending when I got a request to approve another app but I've rejected it as the upstream repo says:

> THIS SERVICE IS NO LONGER MAINTAINED
