### ISSUE TITLE
Become self-contained (cut the nixpkgs-fmt dependency)

### ISSUE THREAD

**Issue by makoConstruct** [nix-community/vscode-nix-ide#340]
The package seems to need nixpkgs-fmt to be installed in order for code formatting to work ([related forum support thread](https://discourse.nixos.org/t/error-with-integration-with-vscode/20848/2)). (This seems to be completely undocumented, which is another issue, but becoming self-contained would obviate that) I think it's clear that it would be better to ship a copy of nixpkgs-fmt in the vscode extension, as it's unlikely that the user will have it installed for any other purpose.

It seems that there is [a wasm version of nixpkgs-fmt](https://github.com/nix-community/nixpkgs-fmt/tree/master/wasm), and I believe vscode can run wasm (on any platform, of course), so we could use that?

Would a pull request, making this change, be accepted?

**Comment by jnoortheen** [comment]
Currently it supports using some Language Server backends (Nil, rnix...) and the nixpkgs-fmt executable for formatting. So packaging a formatter would mean it can format out of the box and for deeper integration one would still need a language server. But we can explore the possibility of packaging the formatter. 

What would be the size of the wasm binary ?

**Comment by jnoortheen** [comment]
Closing this as there are many competing LSP implementations with their own set of pros/cons. Kindly reopen this if anyone is able to explore on this more.
