### ISSUE TITLE
Command to restart language server

### ISSUE THREAD

**Issue by lilyball** [nix-community/vscode-nix-ide#362]
Sometimes I'll get a notification saying the language server crashed 5 times in the past 3 minutes and will not be restarted[^1]. I can't find any way to restart the language server without reloading the whole window. Perhaps this extension could offer a command for the command palette to restart the language server?

[^1]: When I check it's always due to calling `Result::unwrap()` on an `Err` value, usually "EOF while parsing a value" though not always.

**Comment by telometto** [comment]
I'm experiencing the same issue.

**Comment by jnoortheen** [comment]
PRs welcome on it!

**Comment by telometto** [comment]
> PRs welcome on it!

I wish I knew how to fix it 😅
