### ISSUE TITLE
Commenting a line of code uses `//` instead of `#`

### ISSUE THREAD

**Issue by soenkehahn** [nix-community/vscode-nix-ide#374]
When I edit a nix file and execute the 'Add Line Comment' through the command palette, it adds `// ` in front of the line. That's not a valid nix comment though. It should add `# `.

Also, I'm not sure whether the commenting logic is done by this extension or by `nil`, the language server that I'm using. So maybe this is a `nil` bug? How do I find out?

**Comment by jnoortheen** [comment]
I think it should be using the extension's configuration https://github.com/nix-community/vscode-nix-ide/blob/f5db069a77f1dd968e963556c83657d334ddfdd0/language-configuration.json#L4 . You can test this by temporarily disabling the language server

**Comment by soenkehahn** [comment]
What you suggested didn't help, but while looking at the settings I realized I had another nix extension installed. Uninstalling that fixed this for me. Thanks and sorry for the noise!
