### ISSUE TITLE
Feature: Path intellisense 

### ISSUE THREAD

**Issue by n-hass** [nix-community/vscode-nix-ide#379]
I'd like to track the path intellisense feature (mentioned in README) and there didn't seem to be an issue doing so yet :)

I would like to give this a crack, but looking through https://github.com/ChristianKohler/PathIntellisense (and having never written a VS Code extension), it isn't obvious to me what is stopping that plugin from activating in .nix files and/or how this plugin should invoke/prompt the path intellisense plugin.

**Comment by jnoortheen** [comment]
Closing this as the above mentioned plugin now supports `*.nix` files.
