### ISSUE TITLE
Command nil not found in $PATH but it is installed

### ISSUE THREAD

**Issue by nikitavoloboev** [nix-community/vscode-nix-ide#414]
<img width="463" alt="image" src="https://github.com/user-attachments/assets/e8ad0bba-78f7-4afe-a3a7-0618a089f37f">

It's in my shell. So I am confused why it is happening.

My settings in vscode:

```
  "nix.enableLanguageServer": true,
  "nix.serverPath": "nil",
  "nix.formatterPath": "~/.flox/run/aarch64-darwin.default/bin/nixfmt",
  "nix.serverSettings": {
    "nil": {
      "diagnostics": {
        "ignored": ["unused_binding", "unused_with"]
      },
      "formatting": {
        "command": ["nixpkgs-fmt"]
      }
    }
  },
  ```
  
  I see how to hardcode path to formatter but not lsp.

**Comment by nikitavoloboev** [comment]
![CleanShot 2024-08-21 at 18 35 30@2x](https://github.com/user-attachments/assets/19d29190-b5e6-4f09-a580-e7cd9b84c14f)

even added it to `~/.profile`

**Comment by nikitavoloboev** [comment]
Also getting this:

<img width="479" alt="image" src="https://github.com/user-attachments/assets/de9bc0cb-a619-4b4b-85d6-8352fb7841eb">

**Comment by nikitavoloboev** [comment]
ok solved it, it was not in my path with the way I opened the editor

**Comment by saikatdas0790** [comment]
@nikitavoloboev How did you solve this exactly? I'm also running into this same issue when opening VSCode connected to a remote host


![Image](https://github.com/user-attachments/assets/37783ecc-bb1e-44c5-a9e0-a3be9bfb1732)

You can see that the nix profile bin is included in the `$PATH` variable as the first entry.

Howevere, I'm seeing this on VSCode

![Image](https://github.com/user-attachments/assets/1067f555-5feb-4fb5-af53-643aa16495c6)

Any idea why?
