### ISSUE TITLE
"Nix: Restart Language Server" does not allow changing `nix.serverPath`

### ISSUE THREAD

**Issue by ian-h-chamberlain** [nix-community/vscode-nix-ide#419]
I sometimes change my `nix.serverPath` to swap between `nil` and `nixd`, or to point to a different language server version, etc. I had been hoping that the `Restart Language Server` command would work to make this change take effect, but instead it just restarts the previous server with the same path.

This makes sense looking at the implementation https://github.com/nix-community/vscode-nix-ide/blob/main/src/client.ts#L109-L123

Would you be open to changing it to fully deactivate+reactivate the extension, or at least reload `serverOptions` so that changes like these can be picked up? I can try to submit a PR if you'd like as well.

Thanks!

**Comment by jnoortheen** [comment]
I am open to have option to reload the ServerOptions and the LSP client instance.
