### ISSUE TITLE
Delay extension startup until a Nix file is opened

### ISSUE THREAD

**Issue by QuarticCat** [nix-community/vscode-nix-ide#423]
I have some machines that have no Nix environment. I do not use Nix there. This extension keeps popping up "command not found" notifications on VSCode startup even though I haven't opened any Nix file, which is really annoying. Can we delay the startup until a Nix file is opened, just like what clangd extension does?

**Comment by jnoortheen** [comment]
Yes that will be helpful. PRs welcome on this.
