### ISSUE TITLE
Making Formatter Path Configurable

### ISSUE THREAD

**Issue by kclejeune** [nix-community/vscode-nix-ide#60]
Currently, `nixpkgs-fmt` is hard coded as the formatter for all nix files. Ideally, it should be configurable to allow things like `nixfmt` to be used as a drop-in replacements.

**Comment by jnoortheen** [comment]
Contributions are welcome !

**Comment by kclejeune** [comment]
> Contributions are welcome !

This is @kclejeune u io

**Comment by kclejeune** [comment]
> Contributions are welcome !

This is just meant as a placeholder until I can do it after my semester ends :)
